### ISSUE TITLE
Prompt injection agent with chance to get money out of him

### ISSUE THREAD

**Issue by kongzii** [gnosis/prediction-market-agent#563]
> I think we should create a modified version of our general agent where we can play a similar game. The agent holds resources and you can try to extract them from the agent but it costs to send to the agent

**Comment by gabrielfior** [comment]
References
LLM agent (also contracts) -> https://github.com/0xfreysa/agent

-> The agent got beaten because it thought it was a new session and it should obey a new set of commands. Maybe we can try to make it harder and create a new session for every message it receives, so this is always handled.
Also, we can say it should ignore all transactions it receives and only consider messages for making a decision.

**Comment by kongzii** [comment]
Closing this in favor of the whole milestone https://github.com/gnosis/prediction-market-agent/milestone/6
