### ISSUE TITLE
Implement GetPositions functions on microchain agent

### ISSUE THREAD

**Issue by gabrielfior** [gnosis/prediction-market-agent#81]
1. GetUserPositions is Omen-specific, needs to be general
2. getMarket position by ID

@evangriffiths can you please make sure my understanding here is correct, and also if additional functions are still missing? Thanks.

**Comment by evangriffiths** [comment]
Yes that's all I had in mind for now.

1. `GetUserPositions ` currently returns `list[OmenUserPosition]`. This needs to be made market-agnostic. Also `OmenUserPosition` isn't a minimal description of what a user-position is (should return just number shares for each yes/no outcome).
2. As above, but instead of returning a list, should take market id arg, and return a single position.

**Comment by evangriffiths** [comment]
Have left off (2) for now - will play with the microchain agent and determine if this is needed, and make a separate issue for this if so
